### ISSUE TITLE
Begin & Serverless in the JamStack Ecosystem.

### ISSUE THREAD

**Issue by ShawnHosea** [Khaledgarbaya/ama#2]
Where do you see https://begin.com/ in the Jamstack ecosystem? They're fairly new but I think they'll be a major player with what they're offering with spinning up serverless apps so quickly and easily.

**Comment by Khaledgarbaya** [comment]
Hi @ShawnHosea I played a bit with Begin in one of my streams
I think it has great potential. I love how you can keep your code in one repo

Here's the link to the video for more details: https://youtu.be/wxrJU_ZrXy0

**Comment by ShawnHosea** [comment]
Khaled! thanks for the response. I appreciate you taking the time to get back to me. The review was thorough and it was cool watching someone else spin up a Begin app. 💯
