### ISSUE TITLE
11ty JAMstack generator

### ISSUE THREAD

**Issue by jotafelix** [Khaledgarbaya/ama#3]
Hi Khaled!

I would like to know your opinion about 11ty static web generator. I found a visual builder that I can design a site and with an adaptor, transform the site in a static site. (With this tool https://www.udesly.com/webflow-to-netlify/).

I think 11th is not based in React or any JS framework. What do you think about this? it looks like i has all the benefits of JAMStack sites with the help of a design builder.

Looking forward from your respond,
Best!

**Comment by Khaledgarbaya** [comment]
Hey @jotafelix,
I answered your question in this [video](https://youtu.be/aaZn8eX1F7Y)
Here is what I built with 11ty in 30 min https://github.com/Khaledgarbaya/contentful-11ty-example

TLDr; I love it. It allows you to start very simple and flexible enough to scale when your needs grow
